language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules

script:
  - mkdir -p ../.npm-global/lib && ln -s `pwd`/node_modules ../.npm-global/lib/node_modules
  - npm run lint
  - npm run build
