language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules

script:
  - node_modules/.bin/qx compile --machine-readable --target=build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  local-dir: build-output
  on:
    branch: master
